### ISSUE TITLE
リーンキャンバスのライセンス

### ISSUE THREAD

**Issue by kdmsnr** [demi168/Lean-Canvas-prototype-PDF#3]
煩わしいとは思いますが……リーンキャンバスのライセンスは「CC BY-SA 3.0」となっておりますので、クレジットの表記および同ライセンスの適用をお願い致します。
https://creativecommons.org/licenses/by-sa/3.0/deed.ja

**Comment by demi168** [comment]
@kdmsnr 
ご指摘ありがとうございます。
すべてのバージョンに「CC BY-SA 3.0」クレジットを掲載およびライセンスの適用を行いました。

https://github.com/demi168/Lean-Canvas-prototype-PDF/commit/59a8ad694b555dd4e53ffc3aad05416fee8092ae

**Comment by kdmsnr** [comment]
ご対応ありがとうございます。ただ、この場合の「クレジットの表記」とは、書籍の『Running Lean』（オライリー・ジャパン）のことを指しますので、CCのロゴのあたりに併記していただけると助かります。
